CIS_DYNAMODB_PERSON_TABLE: cis-stream-prod-and-idv-IdentityVaultUsers-LMGGZ2XE8K6F
CIS_LOGGING_OUTPUT: cloudwatch
CIS_LOGGING_LEVEL: DEBUG
CIS_CLOUDWATCH_LOG_GROUP: production
SLACK_DRIVER_ENVIRONMENT: production
SLACK_DRIVER_APPSYML: https://cdn.sso.mozilla.com/apps.yml
SLACK_DRIVER_SLACK_APP: Slack
